#!/bin/sh
#
# Plugin to monitor the innodb buffers
#
# Parameters:
#
#       configure
#       autoconf
#
# Configuration variables
#
#       mysqlopts     - Options to pass to mysql
#
# $Log$
#
#
#%# family=auto
#%# capabilities=autoconf

MYSQLOPTS="$mysqlopts"
MYSQLCLIENT=${mysql:-mysql}

if [ "$1" = "autoconf" ]; then
        $MYSQLCLIENT --version 2>/dev/null >/dev/null
        if [ $? -eq 0 ]
        then
                $MYSQLCLIENT $MYSQLOPTS status 2>/dev/null >/dev/null
                if [ $? -eq 0 ]
                then
                        echo yes
                        exit 0
                else
                        echo "no (could not connect to mysql)"
                fi
        else
                echo "no (mysql not found)"
        fi
        exit 1
fi

if [ "$1" = "config" ]; then
        echo 'graph_title InnoDb buffers hits'
        echo 'graph_category mysql'
        echo 'graph_info Gets innodb buffer hit information from the mysql STATUS command'
        echo 'graph_vlabel reads / ${graph_period}'

        echo 'Innodb_buffer_pool_read_requests.label requests'
        echo 'Innodb_buffer_pool_read_requests.draw AREA'
        echo 'Innodb_buffer_pool_read_requests.type DERIVE'
        echo 'Innodb_buffer_pool_read_requests.min 0'
        echo 'Innodb_buffer_pool_read_requests.colour 00B8F5'

        echo 'Innodb_buffer_pool_reads.label disk reads'
        echo 'Innodb_buffer_pool_reads.draw AREA'
        echo 'Innodb_buffer_pool_reads.type DERIVE'
        echo 'Innodb_buffer_pool_reads.min 0'
        echo 'Innodb_buffer_pool_reads.colour FFA600'

        echo 'Innodb_buffer_pool_hit_ratio.graph no'
        echo 'Innodb_buffer_pool_hit_ratio.label hit %'
        echo 'Innodb_buffer_pool_hit_ratio.draw LINE2'
        echo 'Innodb_buffer_pool_hit_ratio.type GAUGE'
        echo 'Innodb_buffer_pool_hit_ratio.min 0'
        echo 'Innodb_buffer_pool_hit_ratio.max 100'
        echo 'Innodb_buffer_pool_hit_ratio.colour FF0000'
        echo 'Innodb_buffer_pool_hit_ratio.cdef 100,Innodb_buffer_pool_reads,Innodb_buffer_pool_read_requests,/,100,*,-'

        exit 0
fi

$MYSQLCLIENT $MYSQLOPTS -e "SHOW STATUS LIKE 'innodb%'" --batch | while read key value; do
        case $key in
                "Innodb_buffer_pool_reads") echo "$key.value $value";
                ;;
                "Innodb_buffer_pool_read_requests") echo "$key.value $value";
                ;;
        esac
done


